import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LocalFont from "next/font/local";
import  { ProviderWrapper } from "@/components/provider/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Univaciti",
  // description: "Generated by create next app",
};

const biome = LocalFont({
  src: [
    {
      path: "../public/fonts/biome/biome-regular.ttf",
      weight: "400",
      style: "normal",
    },
    // {
    //   path: "../../public/fonts/biome/biome-Medium.woff",
    //   weight: "500",
    //   style: "normal",
    // },
    {
      path: "../public/fonts/biome/biome-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-biome",
  display: "swap",
});

const geistLocal = LocalFont({
  src: [
    {
      path: "../public/fonts/geist/Geist-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    // {
    //   path: "../../public/fonts/biome/biome-Medium.woff",
    //   weight: "500",
    //   style: "normal",
    // },
    {
      path: "../public/fonts/geist/Geist-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistLocal.variable}`}>
    <body className={`${geistLocal.variable} } antialiased`}>
      <ProviderWrapper>
        {children}
      </ProviderWrapper>
    </body>
  </html>
  );
}
