export const availableSkills = [
    "JavaScript",
    "Node.js",
    "HTML/CSS",
    "Git/GitHub",
    "Docker",
    "Kubernetes",
    "AWS (Amazon Web Services)",
    "Python",
    "Java",
    "SQL",
    "C++",
    "C#",
    "React",
    "Vue.js",
    "Angular",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "Linux",
    "Bash/Shell Scripting",
    "DevOps",
    "Jenkins",
    "CI/CD Pipelines",
    "Machine Learning",
    "Artificial Intelligence (AI)",
    "Data Science",
    "Data Analysis",
    "TensorFlow",
    "PyTorch",
    "R (Programming Language)",
    "Tableau",
    "Power BI",
    "Salesforce",
    "SAP",
    "Blockchain",
    "Agile Methodologies (Scrum/Kanban)",
    "UI/UX Design",
    "Figma",
    "Adobe XD",
    "Sketch",
    "AutoCAD",
    "MATLAB",
    "Cybersecurity",
    "Ethical Hacking",
    "Penetration Testing",
    "CompTIA A+",
    "Network Administration",
    "ITIL Certification",
    "CCNA (Cisco Certified Network Associate)",
    "PMP (Project Management Professional)",
    "Certified Scrum Master (CSM)",
    "Big Data (Hadoop, Spark)",
  ];

  export const countryOptions = [
    { label: "Afghanistan", value: "Afghanistan" },
    { label: "Albania", value: "Albania" },
    { label: "Algeria", value: "Algeria" },
    { label: "Andorra", value: "Andorra" },
    { label: "Angola", value: "Angola" },
    { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
    { label: "Argentina", value: "Argentina" },
    { label: "Armenia", value: "Armenia" },
    { label: "Australia", value: "Australia" },
    { label: "Austria", value: "Austria" },
    { label: "Azerbaijan", value: "Azerbaijan" },
    { label: "Bahamas", value: "Bahamas" },
    { label: "Bahrain", value: "Bahrain" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Barbados", value: "Barbados" },
    { label: "Belarus", value: "Belarus" },
    { label: "Belgium", value: "Belgium" },
    { label: "Belize", value: "Belize" },
    { label: "Benin", value: "Benin" },
    { label: "Bhutan", value: "Bhutan" },
    { label: "Bolivia", value: "Bolivia" },
    { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
    { label: "Botswana", value: "Botswana" },
    { label: "Brazil", value: "Brazil" },
    { label: "Brunei", value: "Brunei" },
    { label: "Bulgaria", value: "Bulgaria" },
    { label: "Burkina Faso", value: "Burkina Faso" },
    { label: "Burundi", value: "Burundi" },
    { label: "Cabo Verde", value: "Cabo Verde" },
    { label: "Cambodia", value: "Cambodia" },
    { label: "Cameroon", value: "Cameroon" },
    { label: "Canada", value: "Canada" },
    { label: "Central African Republic", value: "Central African Republic" },
    { label: "Chad", value: "Chad" },
    { label: "Chile", value: "Chile" },
    { label: "China", value: "China" },
    { label: "Colombia", value: "Colombia" },
    { label: "Comoros", value: "Comoros" },
    { label: "Costa Rica", value: "Costa Rica" },
    { label: "Croatia", value: "Croatia" },
    { label: "Cuba", value: "Cuba" },
    { label: "Cyprus", value: "Cyprus" },
    { label: "Czech Republic", value: "Czech Republic" },
    { label: "Democratic Republic of the Congo", value: "Democratic Republic of the Congo" },
    { label: "Denmark", value: "Denmark" },
    { label: "Djibouti", value: "Djibouti" },
    { label: "Dominica", value: "Dominica" },
    { label: "Dominican Republic", value: "Dominican Republic" },
    { label: "Ecuador", value: "Ecuador" },
    { label: "Egypt", value: "Egypt" },
    { label: "El Salvador", value: "El Salvador" },
    { label: "Equatorial Guinea", value: "Equatorial Guinea" },
    { label: "Eritrea", value: "Eritrea" },
    { label: "Estonia", value: "Estonia" },
    { label: "Eswatini", value: "Eswatini" },
    { label: "Ethiopia", value: "Ethiopia" },
    { label: "Fiji", value: "Fiji" },
    { label: "Finland", value: "Finland" },
    { label: "France", value: "France" },
    { label: "Gabon", value: "Gabon" },
    { label: "Gambia", value: "Gambia" },
    { label: "Georgia", value: "Georgia" },
    { label: "Germany", value: "Germany" },
    { label: "Ghana", value: "Ghana" },
    { label: "Greece", value: "Greece" },
    { label: "Grenada", value: "Grenada" },
    { label: "Guatemala", value: "Guatemala" },
    { label: "Guinea", value: "Guinea" },
    { label: "Guinea-Bissau", value: "Guinea-Bissau" },
    { label: "Guyana", value: "Guyana" },
    { label: "Haiti", value: "Haiti" },
    { label: "Honduras", value: "Honduras" },
    { label: "Hungary", value: "Hungary" },
    { label: "Iceland", value: "Iceland" },
    { label: "India", value: "India" },
    { label: "Indonesia", value: "Indonesia" },
    { label: "Iran", value: "Iran" },
    { label: "Iraq", value: "Iraq" },
    { label: "Ireland", value: "Ireland" },
    { label: "Israel", value: "Israel" },
    { label: "Italy", value: "Italy" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Japan", value: "Japan" },
    { label: "Jordan", value: "Jordan" },
    { label: "Kazakhstan", value: "Kazakhstan" },
    { label: "Kenya", value: "Kenya" },
    { label: "Kiribati", value: "Kiribati" },
    { label: "Kuwait", value: "Kuwait" },
    { label: "Kyrgyzstan", value: "Kyrgyzstan" },
    { label: "Laos", value: "Laos" },
    { label: "Latvia", value: "Latvia" },
    { label: "Lebanon", value: "Lebanon" },
    { label: "Lesotho", value: "Lesotho" },
    { label: "Liberia", value: "Liberia" },
    { label: "Libya", value: "Libya" },
    { label: "Liechtenstein", value: "Liechtenstein" },
    { label: "Lithuania", value: "Lithuania" },
    { label: "Luxembourg", value: "Luxembourg" },
    { label: "Madagascar", value: "Madagascar" },
    { label: "Malawi", value: "Malawi" },
    { label: "Malaysia", value: "Malaysia" },
    { label: "Maldives", value: "Maldives" },
    { label: "Mali", value: "Mali" },
    { label: "Malta", value: "Malta" },
    { label: "Marshall Islands", value: "Marshall Islands" },
    { label: "Mauritania", value: "Mauritania" },
    { label: "Mauritius", value: "Mauritius" },
    { label: "Mexico", value: "Mexico" },
    { label: "Micronesia", value: "Micronesia" },
    { label: "Moldova", value: "Moldova" },
    { label: "Monaco", value: "Monaco" },
    { label: "Mongolia", value: "Mongolia" },
    { label: "Montenegro", value: "Montenegro" },
    { label: "Morocco", value: "Morocco" },
    { label: "Mozambique", value: "Mozambique" },
    { label: "Myanmar", value: "Myanmar" },
    { label: "Namibia", value: "Namibia" },
    { label: "Nauru", value: "Nauru" },
    { label: "Nepal", value: "Nepal" },
    { label: "Netherlands", value: "Netherlands" },
    { label: "New Zealand", value: "New Zealand" },
    { label: "Nicaragua", value: "Nicaragua" },
    { label: "Niger", value: "Niger" },
    { label: "Nigeria", value: "Nigeria" },
    { label: "North Korea", value: "North Korea" },
    { label: "North Macedonia", value: "North Macedonia" },
    { label: "Norway", value: "Norway" },
    { label: "Oman", value: "Oman" },
    { label: "Pakistan", value: "Pakistan" },
    { label: "Palau", value: "Palau" },
    { label: "Panama", value: "Panama" },
    { label: "Papua New Guinea", value: "Papua New Guinea" },
    { label: "Paraguay", value: "Paraguay" },
    { label: "Peru", value: "Peru" },
    { label: "Philippines", value: "Philippines" },
    { label: "Poland", value: "Poland" },
    { label: "Portugal", value: "Portugal" },
    { label: "Qatar", value: "Qatar" },
    { label: "Republic of the Congo", value: "Republic of the Congo" },
    { label: "Romania", value: "Romania" },
    { label: "Russia", value: "Russia" },
    { label: "Rwanda", value: "Rwanda" },
    { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
    { label: "Saint Lucia", value: "Saint Lucia" },
    { label: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines" },
    { label: "Samoa", value: "Samoa" },
    { label: "San Marino", value: "San Marino" },
    { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
    { label: "Saudi Arabia", value: "Saudi Arabia" },
    { label: "Senegal", value: "Senegal" },
    { label: "Serbia", value: "Serbia" },
    { label: "Seychelles", value: "Seychelles" },
    { label: "Sierra Leone", value: "Sierra Leone" },
    { label: "Singapore", value: "Singapore" },
    { label: "Slovakia", value: "Slovakia" },
    { label: "Slovenia", value: "Slovenia" },
    { label: "Solomon Islands", value: "Solomon Islands" },
    { label: "Somalia", value: "Somalia" },
    { label: "South Africa", value: "South Africa" },
    { label: "South Korea", value: "South Korea" },
    { label: "South Sudan", value: "South Sudan" },
    { label: "Spain", value: "Spain" },
    { label: "Sri Lanka", value: "Sri Lanka" },
    { label: "Sudan", value: "Sudan" },
    { label: "Suriname", value: "Suriname" },
    { label: "Sweden", value: "Sweden" },
    { label: "Switzerland", value: "Switzerland" },
    { label: "Syria", value: "Syria" },
    { label: "Taiwan", value: "Taiwan" },
    { label: "Tajikistan", value: "Tajikistan" },
    { label: "Tanzania", value: "Tanzania" },
    { label: "Thailand", value: "Thailand" },
    { label: "Timor-Leste", value: "Timor-Leste" },
    { label: "Togo", value: "Togo" },
    { label: "Tonga", value: "Tonga" },
    { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
    { label: "Tunisia", value: "Tunisia" },
    { label: "Turkey", value: "Turkey" },
    { label: "Turkmenistan", value: "Turkmenistan" },
    { label: "Tuvalu", value: "Tuvalu" },
    { label: "Uganda", value: "Uganda" },
    { label: "Ukraine", value: "Ukraine" },
    { label: "United Arab Emirates", value: "United Arab Emirates" },
    { label: "United Kingdom", value: "United Kingdom" },
    { label: "United States of America", value: "United States of America" },
    { label: "Uruguay", value: "Uruguay" },
    { label: "Uzbekistan", value: "Uzbekistan" },
    { label: "Vanuatu", value: "Vanuatu" },
    { label: "Vatican City", value: "Vatican City" },
    { label: "Venezuela", value: "Venezuela" },
    { label: "Vietnam", value: "Vietnam" },
    { label: "Yemen", value: "Yemen" },
    { label: "Zambia", value: "Zambia" },
    { label: "Zimbabwe", value: "Zimbabwe" }
  ]

  export const ageOptions = Array.from({ length: 40 - 16 + 1 }, (_, i) => ({
    label: `${i + 16} years`,
    value: `${i + 16}`,
  }));
  

  export const universityOptions = [
    { label: "University of Lagos (UNILAG)", value: "University of Lagos" },
    { label: "University of Ibadan (UI)", value: "University of Ibadan" },
    { label: "University of Nigeria, Nsukka (UNN)", value: "University of Nigeria, Nsukka" },
    { label: "Ahmadu Bello University (ABU), Zaria", value: "Ahmadu Bello University" },
    { label: "University of Ilorin (UNILORIN)", value: "University of Ilorin" },
    { label: "Obafemi Awolowo University (OAU), Ile-Ife", value: "Obafemi Awolowo University" },
    { label: "University of Port Harcourt (UNIPORT)", value: "University of Port Harcourt" },
    { label: "Lagos State University (LASU)", value: "Lagos State University" },
    { label: "Covenant University, Ota", value: "Covenant University" },
    { label: "Federal University of Technology, Akure (FUTA)", value: "Federal University of Technology, Akure" },
    { label: "University of Benin (UNIBEN)", value: "University of Benin" },
    { label: "Bayero University, Kano (BUK)", value: "Bayero University" },
    { label: "Federal University of Technology, Minna (FUTMINNA)", value: "Federal University of Technology, Minna" },
    { label: "Federal University of Agriculture, Abeokuta (FUNAAB)", value: "Federal University of Agriculture, Abeokuta" },
    { label: "Ahmadu Bello University, Zaria", value: "Ahmadu Bello University, Zaria" },
    { label: "Landmark University, Omu-Aran", value: "Landmark University" },
    { label: "Babcock University, Ilishan-Remo", value: "Babcock University" },
    { label: "Afe Babalola University, Ado-Ekiti (ABUAD)", value: "Afe Babalola University" },
    { label: "Federal University, Oye-Ekiti (FUOYE)", value: "Federal University Oye-Ekiti" },
    { label: "Alex Ekwueme Federal University, Ndufu-Alike", value: "Alex Ekwueme Federal University" },
    { label: "Obafemi Awolowo University, Ile-Ife", value: "Obafemi Awolowo University, Ile-Ife" },
    { label: "University of Abuja (UNIABUJA)", value: "University of Abuja" },
    { label: "Ajayi Crowther University, Ibadan", value: "Ajayi Crowther University" },
    { label: "Bowen University, Iwo", value: "Bowen University" },
    { label: "Benson Idahosa University, Benin City", value: "Benson Idahosa University" },
    { label: "Madonna University, Okija", value: "Madonna University" },
    { label: "Lead City University, Ibadan", value: "Lead City University" },
    { label: "Crescent University, Abeokuta", value: "Crescent University" },
    { label: "Caleb University, Lagos", value: "Caleb University" },
    { label: "Caritas University, Enugu", value: "Caritas University" },
    { label: "Crawford University, Igbesa", value: "Crawford University" },
    { label: "American University of Nigeria (AUN), Yola", value: "American University of Nigeria" },
    { label: "Bells University of Technology, Otta", value: "Bells University of Technology" },
    { label: "Igbinedion University, Okada", value: "Igbinedion University" },
    { label: "Gregory University, Uturu", value: "Gregory University" },
    { label: "Usmanu Danfodiyo University, Sokoto (UDUS)", value: "Usmanu Danfodiyo University" },
    { label: "University of Jos (UNIJOS)", value: "University of Jos" },
    { label: "University of Calabar (UNICAL)", value: "University of Calabar" },
    { label: "University of Maiduguri (UNIMAID)", value: "University of Maiduguri" },
    { label: "University of Uyo (UNIUYO)", value: "University of Uyo" },
    { label: "Rivers State University, Port Harcourt", value: "Rivers State University" },
    { label: "Delta State University, Abraka", value: "Delta State University" },
    { label: "Enugu State University of Science & Technology (ESUT)", value: "Enugu State University of Science & Technology" },
    { label: "Ekiti State University, Ado-Ekiti", value: "Ekiti State University" },
    { label: "Ambrose Alli University, Ekpoma", value: "Ambrose Alli University" },
    { label: "Imo State University, Owerri", value: "Imo State University" },
    { label: "Ebonyi State University, Abakaliki", value: "Ebonyi State University" },
    { label: "Benue State University, Makurdi", value: "Benue State University" },
    { label: "Kano University of Science & Technology, Wudil", value: "Kano University of Science & Technology" },
    { label: "Akwa Ibom State University, Ikot-Akpaden", value: "Akwa Ibom State University" },
    { label: "Others", value: "Others" },
  ];
  

  export const fieldsOptions = [
    { label: "Accounting", value: "Accounting" },
    { label: "Actuarial Science", value: "Actuarial Science" },
    { label: "Agriculture", value: "Agriculture" },
    { label: "Agricultural Economics", value: "Agricultural Economics" },
    { label: "Agricultural Engineering", value: "Agricultural Engineering" },
    { label: "Animal Science", value: "Animal Science" },
    { label: "Architecture", value: "Architecture" },
    { label: "Banking & Finance", value: "Banking & Finance" },
    { label: "Biochemistry", value: "Biochemistry" },
    { label: "Biological Sciences", value: "Biological Sciences" },
    { label: "Biotechnology", value: "Biotechnology" },
    { label: "Botany", value: "Botany" },
    { label: "Business Administration", value: "Business Administration" },
    { label: "Chemical Engineering", value: "Chemical Engineering" },
    { label: "Chemistry", value: "Chemistry" },
    { label: "Civil Engineering", value: "Civil Engineering" },
    { label: "Computer Science", value: "Computer Science" },
    { label: "Information Technology", value: "Information Technology" },
    { label: "Cybersecurity", value: "Cybersecurity" },
    { label: "Software Engineering", value: "Software Engineering" },
    { label: "Communication & Media Studies", value: "Communication & Media Studies" },
    { label: "Criminology", value: "Criminology" },
    { label: "Cultural Studies", value: "Cultural Studies" },
    { label: "Dentistry", value: "Dentistry" },
    { label: "Economics", value: "Economics" },
    { label: "Education", value: "Education" },
    { label: "Electrical Engineering", value: "Electrical Engineering" },
    { label: "Electronics Engineering", value: "Electronics Engineering" },
    { label: "English", value: "English" },
    { label: "Environmental Science", value: "Environmental Science" },
    { label: "Environmental Engineering", value: "Environmental Engineering" },
    { label: "Food Science & Technology", value: "Food Science & Technology" },
    { label: "Forestry", value: "Forestry" },
    { label: "Geography", value: "Geography" },
    { label: "Geology", value: "Geology" },
    { label: "History & International Studies", value: "History & International Studies" },
    { label: "Human Resource Management", value: "Human Resource Management" },
    { label: "Industrial Chemistry", value: "Industrial Chemistry" },
    { label: "Industrial Mathematics", value: "Industrial Mathematics" },
    { label: "Industrial Physics", value: "Industrial Physics" },
    { label: "Industrial Relations", value: "Industrial Relations" },
    { label: "International Relations", value: "International Relations" },
    { label: "Law", value: "Law" },
    { label: "Library & Information Science", value: "Library & Information Science" },
    { label: "Linguistics", value: "Linguistics" },
    { label: "Marketing", value: "Marketing" },
    { label: "Mass Communication", value: "Mass Communication" },
    { label: "Mechanical Engineering", value: "Mechanical Engineering" },
    { label: "Medical Laboratory Science", value: "Medical Laboratory Science" },
    { label: "Medicine & Surgery", value: "Medicine & Surgery" },
    { label: "Microbiology", value: "Microbiology" },
    { label: "Nursing", value: "Nursing" },
    { label: "Pharmacy", value: "Pharmacy" },
    { label: "Philosophy", value: "Philosophy" },
    { label: "Physics", value: "Physics" },
    { label: "Political Science", value: "Political Science" },
    { label: "Project Management", value: "Project Management" },
    { label: "Psychology", value: "Psychology" },
    { label: "Public Administration", value: "Public Administration" },
    { label: "Public Health", value: "Public Health" },
    { label: "Quantity Surveying", value: "Quantity Surveying" },
    { label: "Religious Studies", value: "Religious Studies" },
    { label: "Sociology", value: "Sociology" },
    { label: "Soil Science", value: "Soil Science" },
    { label: "Statistics", value: "Statistics" },
    { label: "Theatre Arts", value: "Theatre Arts" },
    { label: "Urban & Regional Planning", value: "Urban & Regional Planning" },
    { label: "Veterinary Medicine", value: "Veterinary Medicine" },
    { label: "Zoology", value: "Zoology" },
  
    // Newer NUC-approved degrees
    { label: "Artificial Intelligence", value: "Artificial Intelligence" },
    { label: "Data Science", value: "Data Science" },
    { label: "Machine Learning", value: "Machine Learning" },
    { label: "Nuclear Science", value: "Nuclear Science" },
    { label: "Nuclear Engineering", value: "Nuclear Engineering" },
    { label: "Telecommunication Science", value: "Telecommunication Science" },
    { label: "Intelligence & Security Studies", value: "Intelligence & Security Studies" },
    { label: "Community Health Sciences", value: "Community Health Sciences" },
    { label: "Water, Sanitation & Hygiene (WASH)", value: "Water, Sanitation & Hygiene (WASH)" },
    { label: "Others", value: "Others" },
  ];
  
  export const degreeTypes = [
    { label: "BA (Bachelor of Arts)", value: "BA" },
    { label: "BEng (Bachelor of Engineering)", value: "BEng" },
    { label: "BTech (Bachelor of Technology)", value: "BTech" },
    { label: "LLB (Bachelor of Law)", value: "LLB" },
    { label: "BSc.Ed", value: "BSc.Ed" },
     { label: "HND", value: "HND" },
    { label: "ND", value: "ND" },
    { label: "BSc (Bachelor of Science)", value: "BSc" },
    { label: "BA.Ed", value: "BA.Ed" },
    { label: "PGD (Postgraduate Diploma)", value: "PGD" },
    { label: "PGDE (Postgraduate Diploma in Education)", value: "PGDE" },
    { label: "MSc (Master of Science)", value: "MSc" },
    { label: "MA (Master of Arts)", value: "MA" },
    { label: "MEng (Master of Engineering)", value: "MEng" },
    { label: "MBA (Master of Business Administration)", value: "MBA" },
    { label: "LLM (Master of Laws)", value: "LLM" },
    { label: "Others", value: "Others" },
  ];
  

  export const finalGradeOptions = [
    { label: "First Class", value: "First class" },
    { label: "Second Class Upper (2:1)", value: "Second class upper" },
    { label: "Second Class Lower (2:2)", value: "Second_class_lower" },
    { label: "Third Class", value: "Third_class" },
    { label: "Pass", value: "Pass" },
    { label: "Not applicable", value: "Not applicable" },
  ];
  
  export const jobRolesOptions = [
    { label: "Software Engineer", value: "software_engineer" },
    { label: "Frontend Developer", value: "frontend_developer" },
    { label: "Backend Developer", value: "backend_developer" },
    { label: "Full Stack Developer", value: "full_stack_developer" },
    { label: "Mobile App Developer", value: "mobile_app_developer" },
    { label: "Cloud Engineer", value: "cloud_engineer" },
    { label: "DevOps Engineer", value: "devops_engineer" },
    { label: "Data Analyst", value: "data_analyst" },
    { label: "Data Scientist", value: "data_scientist" },
    { label: "Machine Learning Engineer", value: "machine_learning_engineer" },
    { label: "AI Engineer", value: "ai_engineer" },
    { label: "Cybersecurity Analyst", value: "cybersecurity_analyst" },
    { label: "Blockchain Developer", value: "blockchain_developer" },
    { label: "Product Manager", value: "product_manager" },
    { label: "Project Manager", value: "project_manager" },
    { label: "Business Analyst", value: "business_analyst" },
    { label: "UI/UX Designer", value: "ui_ux_designer" },
    { label: "Graphic Designer", value: "graphic_designer" },
    { label: "Content Strategist", value: "content_strategist" },
    { label: "Digital Marketer", value: "digital_marketer" },
    { label: "Marketing Manager", value: "marketing_manager" },
    { label: "Financial Analyst", value: "financial_analyst" },
    { label: "Investment Analyst", value: "investment_analyst" },
    { label: "Accountant", value: "accountant" },
    { label: "Auditor", value: "auditor" },
    { label: "Human Resources Manager", value: "human_resources_manager" },
    { label: "Operations Manager", value: "operations_manager" },
    { label: "Supply Chain Manager", value: "supply_chain_manager" },
    { label: "Management Consultant", value: "management_consultant" },
    { label: "Lawyer", value: "lawyer" },
    { label: "Doctor", value: "doctor" },
    { label: "Nurse", value: "nurse" },
    { label: "Pharmacist", value: "pharmacist" },
    { label: "Public Health Officer", value: "public_health_officer" },
    { label: "Research Scientist", value: "research_scientist" },
    { label: "Psychologist", value: "psychologist" },
    { label: "Economist", value: "economist" },
    { label: "Architect", value: "architect" },
    { label: "Civil Engineer", value: "civil_engineer" },
    { label: "Mechanical Engineer", value: "mechanical_engineer" },
    { label: "Electrical Engineer", value: "electrical_engineer" },
    { label: "Chemical Engineer", value: "chemical_engineer" },
    { label: "Petroleum Engineer", value: "petroleum_engineer" },
    { label: "Teacher", value: "teacher" },
    { label: "Lecturer", value: "lecturer" },
    { label: "Entrepreneur", value: "entrepreneur" }
  ]

  
  export const graduationYears = Array.from(
    { length: new Date().getFullYear() - 1990 },
    (_, i) => {
      const year = 1990 + i;
      return { label: String(year), value: String(year) };
    }
  );
  

 export const experienceOptions= [
    { label: "0 - 2 years", value: "0-2" },
    { label: "2 - 5 years", value: "2-5" },
    { label: "5 - 7 years", value: "5-7" },
    { label: "7 - 10 years", value: "7-10" }
  ]
  

  export const specializationOptions = [
    { label: "AI & Machine Learning", value: "Ai" },
    { label: "Data Science & Analytics", value: "Data Analytics" },
    { label: "Cloud Engineering", value: "Cloud Engineering" },
    { label: "Software Engineering", value: "software_engineering" },
    { label: "React", value: "React" },
    { label: "DevOps & SRE", value: "DevOps" },
    { label: "Cloud Architecture", value: "cloud_architecture" },
    { label: "Java", value: "Java" },
    { label: "Quality Assurance & Testing", value: "quality_assurance_testing" },
    { label: "Project Management", value: "project_management" },
  ];
  